commonLabels:
  app: ramya-nginx

replicaCount: 2
service:
  type: clusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: ramya-nginx.sctp-sandbox.com
  hosts:
    - host: ramya-nginx.sctp-sandbox.com
      paths:
        - path: /
          pathType: Prefix
  tls: true